site_name: Weather and Artifical Intelligence

site_description: The course "Weather and Artificial Intelligence" at Dept. Atm, NCU.

site_author: 1chooo(Hugo ChunHo Lin)

site_url: https://1chooo.github.io/weather-ai/

repo_url: https://github.com/1chooo/weather-ai

copyright: Copyright &copy; 2023 1chooo (Hugo ChunHo Lin)

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - navigation.top
        - navigation.tabs
        # - navigation.sections
        # - navigation.indexes
        # - search.highlight
        # - navigation.expand
        # - navigation.tabs
    # favicon: assets/favicon.ico
    icon:
        logo: logo

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
        include_source: True
        execute: True
        # validate_nb: True
        #   ignore_h1_titles: True
        #   execute_ignore: "*.ipynb"

markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
        linenums: true
    - toc:
        permalink: true


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/1chooo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/1chooo___
    # - icon: fas fa-rss
    #   link: https://sites.google.com/g.ncu.edu.tw/1chooo/portfolio?authuser=0
    # - icon: fab fa-linkedin
    #   link: https://www.linkedin.com/in/1chooo/
    # conda_env: py38
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X



nav:
    - Home: index.md
      #- Installation: installation.md
    - Usage: usage.md
    # - Fortran Basic:
    #     - fortran_basic/01_hello_world.md
    # - Python Basic:
    #     - python_basic/01_hello_world.ipynb
    - Example:
        - example/env_test.ipynb
    - Contributing: contributing.md
      #- FAQ: faq.md
      #- Changelog: changelog.md
      #- Example: example.md
    - Reference: reference.md
    - Report Issues: https://github.com/1chooo/weather-ai/issues
