site_name: Weather and Artifical Intelligence

site_description: The course "Weather and Artificial Intelligence" at Dept. Atm, NCU.

site_author: 1chooo(Hugo ChunHo Lin)

site_url: https://1chooo.github.io/weather-ai/

repo_url: https://github.com/1chooo/weather-ai

copyright: Copyright &copy; 2023 1chooo (Hugo ChunHo Lin)

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - navigation.top
        - navigation.tabs
        # - navigation.sections
        # - navigation.indexes
        # - search.highlight
        # - navigation.expand
        # - navigation.tabs
    icon:
        logo: logo

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
        include_source: True
        execute: False
        # ignore: [""]
        # validate_nb: True
        #   ignore_h1_titles: True
        #   execute_ignore: "*.ipynb"

markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
        linenums: true
    - toc:
        permalink: true


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/1chooo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/1chooo___

nav:
    - Home: index.md
    - Test: env_test.py
    - Course Materials: course_materials.md
    - Course Source Code:
      - Python Basic:
        - python_basic/01_hello_world.py
      - Machine Learning:
        - CH01:
          - machine_learning/ch01/01_evaluation_index.py
          - machine_learning/ch01/02_regression_model.py
          - machine_learning/ch01/03_lasso_ridge.py
          - machine_learning/ch01/04_decision_tree.py
          - machine_learning/ch01/05_random_forest.py
          - machine_learning/ch01/06_gradient_boosting_machine.py
        - CH02:
          - machine_learning/ch02/01_data_cleaning.py
      - Deep Learning:
        - CH02:
          - deep_learning/ch02/01_tensors_intro.py
          - deep_learning/ch02/02_tensor_operation.py
          - deep_learning/ch02/03_handwriting.py
        - CH03:
          - deep_learning/ch03/01_binary_classification.py
          - deep_learning/ch03/02_multiclass_classification.py
          - deep_learning/ch03/03_regression.py
        - CH04:
          - deep_learning/ch04/01_binary_classification_overfitting.py
          - deep_learning/ch04/02_evaluate.py
        - CH05:
          - deep_learning/ch05/01_mnist.py
    - Archive:
      - 2023 Spring:
        - Course Materials: archive/2023_spring/course_materials/index.md
        - Intro: archive/2023_spring/intro/23_spring_hw_intro.md
        - HW01:
          - archive/2023_spring/hw01/23_spring_hw01_description.md
          - archive/2023_spring/hw01/23_spring_hw01_cifar10_DNN.py
          - archive/2023_spring/hw01/23_spring_hw01_cifar10_CNN.py
          - archive/2023_spring/hw01/23_spring_hw01_cifar10_byChatGPT.py
        - HW02:
          - archive/2023_spring/hw02/23_spring_hw02_description.md
          - archive/2023_spring/hw02/23_spring_hw02_cifar10_data_aug.py

    - Contributing: contributing.md
    - Reference: reference.md
    - Report Issues: https://github.com/1chooo/weather-ai/issues
